import type { TemplatePayload } from "../../types/artifacts.js";

export function actionsTemplate(payload: TemplatePayload): string {
  const { featureName, timestamp } = payload;
  return [
    `# Actions: ${featureName}`,
    "",
    "## Pre-requisites",
    "- [ ] <!-- prerequisite 1 -->",
    "- [ ] <!-- prerequisite 2 -->",
    "",
    "## Action List",
    "",
    "### A001: <!-- action title -->",
    "- **Type**: `create | modify | delete | investigate`",
    "- **Target**: `path/to/target.ts`",
    "- **Description**: <!-- what this action does -->",
    "- **Acceptance**: <!-- how to verify this action is done correctly -->",
    "- **Risk**: low | medium | high",
    "- **Estimated Effort**: S | M | L | XL",
    "- **Dependencies**: <!-- action IDs this depends on, comma-separated -->",
    "- **Status**: [ ] <!-- not started -->",
    "",
    "### A002: <!-- action title -->",
    "- **Type**: `create | modify | delete | investigate`",
    "- **Target**: `path/to/target.ts`",
    "- **Description**: <!-- what this action does -->",
    "- **Acceptance**: <!-- how to verify this action is done correctly -->",
    "- **Risk**: low | medium | high",
    "- **Estimated Effort**: S | M | L | XL",
    "- **Dependencies**: A001",
    "- **Status**: [ ] <!-- not started -->",
    "",
    "## Rollback Plan",
    "<!-- How to revert the feature if needed -->",
    "- ",
    "",
    "---",
    "",
    `*Generated: ${timestamp}*`,
    "*Completion: 0%*",
    "",
  ].join("\n");
}
