import type { TemplatePayload } from "../../types/artifacts.js";

export function requirementsTemplate(payload: TemplatePayload): string {
  const { featureName, featureId, timestamp } = payload;
  return [
    `# Feature: ${featureName} (${featureId})`,
    "",
    "> Spec-Driven Development: entender → especificar → planejar → testar → implementar → verificar.",
    "",
    "## Descrição Funcional",
    "<!-- Descreva o que esta feature faz, em linguagem de negócio. Qual problema resolve? -->",
    "",
    "## Comportamento Esperado",
    "<!-- Como o sistema deve se comportar quando a feature estiver implementada? -->",
    "",
    "## Invariantes de Domínio",
    "<!-- Regras que SEMPRE devem ser verdadeiras, independente do estado do sistema. -->",
    "- ",
    "",
    "## Entradas",
    "<!-- Dados de entrada, parâmetros, payloads. -->",
    "- ",
    "",
    "## Saídas",
    "<!-- Dados de saída, respostas, efeitos colaterais esperados. -->",
    "- ",
    "",
    "## Regras de Negócio",
    "<!-- Regras de negócio específicas desta feature. -->",
    "- R01: ",
    "- R02: ",
    "",
    "## Dados Persistidos",
    "<!-- O que será armazenado? Onde? Em qual formato? -->",
    "- ",
    "",
    "## Integrações Externas",
    "<!-- APIs, serviços, sistemas externos afetados. -->",
    "- ",
    "",
    "## Critérios de Aceitação",
    "<!-- Formato Given/When/Then. Devem ser mensuráveis e testáveis. -->",
    "- [ ] **Cenário 1:** Given <!-- contexto -->, When <!-- ação -->, Then <!-- resultado esperado -->",
    "- [ ] **Cenário 2:** Given <!-- contexto -->, When <!-- ação -->, Then <!-- resultado esperado -->",
    "- [ ] **Cenário 3:** Given <!-- contexto -->, When <!-- ação -->, Then <!-- resultado esperado -->",
    "",
    "## Casos de Erro",
    "<!-- O que acontece em cada cenário de erro? -->",
    "- **Erro 1:** <!-- descrição → comportamento esperado -->",
    "- **Erro 2:** <!-- descrição → comportamento esperado -->",
    "",
    "## Casos Extremos",
    "<!-- Edge cases: valores nulos, limites, condições de corrida, timeouts. -->",
    "- [ ] <!-- edge case 1 -->",
    "- [ ] <!-- edge case 2 -->",
    "",
    "## Restrições Técnicas",
    "<!-- Limitações técnicas, versões, compatibilidade. -->",
    "- ",
    "",
    "## Escopo Negativo",
    "<!-- EXPLICITAMENTE: o que NÃO está incluso nesta feature. -->",
    "- Esta feature NÃO inclui: <!-- descrever -->",
    "- Esta feature NÃO inclui: <!-- descrever -->",
    "",
    "## Requisitos Não-Funcionais",
    "<!-- Performance, segurança, escalabilidade, observabilidade. -->",
    "- **Performance:** <!-- requisito -->",
    "- **Segurança:** <!-- requisito -->",
    "- **Observabilidade:** <!-- requisito -->",
    "",
    "## Riscos de Manutenção",
    "<!-- O que pode quebrar no futuro? O que é sensível a mudanças? -->",
    "- **Risco 1:** <!-- descrição → mitigação -->",
    "- **Risco 2:** <!-- descrição → mitigação -->",
    "",
    "## Dúvidas [DOUBT]",
    "<!-- Marcadores [DOUBT] bloqueiam avanço além de feature-requirements. -->",
    "<!-- Resolva com `devflow clarify` ou manualmente. -->",
    "- [ ] [DOUBT] <!-- pergunta -->",
    "",
    "---",
    "",
    `*Gerado: ${timestamp}*`,
    "*Status: Draft — requer revisão de requirements*",
    "",
  ].join("\n");
}
