import type { TemplatePayload } from "../../types/artifacts.js";

export function requirementsTemplate(payload: TemplatePayload): string {
  const { featureName, featureId, timestamp } = payload;
  return [
    `# Feature: ${featureName} (${featureId})`,
    "",
    "## Overview",
    "<!-- Describe the feature in one paragraph. What problem does it solve? -->",
    "",
    "## Motivation",
    "<!-- Why is this feature needed? What user/business need does it address? -->",
    "",
    "## Success Criteria",
    "- [ ] <!-- measurable criterion 1 -->",
    "- [ ] <!-- measurable criterion 2 -->",
    "- [ ] <!-- measurable criterion 3 -->",
    "",
    "## Out of Scope",
    "<!-- Explicitly list what this feature does NOT include -->",
    "- ",
    "",
    "## Dependencies",
    "<!-- Other features, systems, or teams this depends on -->",
    "- ",
    "",
    "## Constraints",
    "<!-- Technical, timeline, or resource constraints -->",
    "- ",
    "",
    "## Questions / [DOUBT]",
    "<!-- Mark ambiguous items with [DOUBT] for clarification -->",
    "- [ ] [DOUBT] <!-- unclear requirement -->",
    "",
    "## Stakeholders",
    "<!-- People to involve in review -->",
    "- ",
    "",
    "---",
    "",
    `*Generated: ${timestamp}*`,
    "*Status: Draft*",
    "",
  ].join("\n");
}
