import type { TemplatePayload } from "../../types/artifacts.js";

export function roadmapTemplate(payload: TemplatePayload): string {
  const { featureName, timestamp } = payload;
  return [
    `# Architectural Roadmap: ${featureName}`,
    "",
    "> Este documento define COMO a feature será implementada, não apenas O QUE ela faz.",
    "",
    "## Desenho Arquitetural",
    "```mermaid",
    "<!-- Diagrama de arquitetura: componentes, relações, fluxo de dados -->",
    "```",
    "",
    "## Camadas Envolvidas",
    "<!-- Quais camadas da arquitetura esta feature toca? -->",
    "- [ ] Domínio (entidades, value objects, agregados)",
    "- [ ] Aplicação (use cases, serviços de aplicação)",
    "- [ ] Infraestrutura (repositories, adapters, clientes HTTP)",
    "- [ ] Interface (controllers, CLI commands, handlers)",
    "",
    "## Classes/Módulos Previstos",
    "<!-- Cada classe/módulo com sua responsabilidade única (SRP). -->",
    "| Classe/Módulo | Responsabilidade | Camada |",
    "|--------------|-----------------|--------|",
    "| `<!-- NomeClasse -->` | `<!-- responsabilidade única -->` | `<!-- camada -->` |",
    "",
    "## Padrões de Projeto Adotados",
    "<!-- Quais padrões e POR QUE. -->",
    "- **Padrão:** <!-- nome → justificativa -->",
    "- **Padrão:** <!-- nome → justificativa -->",
    "",
    "## Padrões Rejeitados",
    "<!-- Padrões considerados mas rejeitados, com justificativa. -->",
    "- **Padrão:** <!-- nome → por que foi rejeitado -->",
    "",
    "## Interfaces Necessárias",
    "<!-- Contratos que as implementações devem satisfazer. -->",
    "```typescript",
    "// interface IUserRepository { ... }",
    "// interface INotificationService { ... }",
    "```",
    "",
    "## Repositories",
    "<!-- Abstrações de persistência. -->",
    "- `<!-- IEntityRepository -->` — responsável por <!-- entidade -->",
    "",
    "## Adapters",
    "<!-- Adaptadores para infraestrutura externa. -->",
    "- `<!-- NomeAdapter -->` — implementa `<!-- interface -->` usando `<!-- tecnologia -->`",
    "",
    "## Serviços de Domínio",
    "<!-- Serviços que orquestram regras de negócio entre entidades. -->",
    "- `<!-- NomeService -->` — responsável por <!-- regra de negócio -->",
    "",
    "## Riscos de Acoplamento",
    "<!-- Onde o acoplamento pode surgir e como mitigar. -->",
    "- **Risco:** <!-- dependência → mitigação -->",
    "",
    "## Impacto em Código Legado",
    "<!-- Arquivos existentes afetados, riscos de regressão. -->",
    "| Arquivo | Tipo de Mudança | Risco |",
    "|---------|---------------|------|",
    "| `<!-- path -->` | `<!-- mod/create/delete -->` | `<!-- low/medium/high -->` |",
    "",
    "## Estratégia de Rollback",
    "<!-- Como desfazer esta feature se necessário. -->",
    "- Reverter merge da branch `feature/<!-- nome -->`",
    "- Executar script de rollback: `<!-- comando -->` (se aplicável)",
    "",
    "## Verificação de Constitution",
    "<!-- Checklist de conformidade com a constitution do projeto. -->",
    "- [ ] C1 — Regras de negócio encapsuladas em domínio/serviços/use cases",
    "- [ ] C2 — Infraestrutura acessada por interfaces/adapters/repositories",
    "- [ ] C3 — Dependências apontam para dentro (inner layers não dependem de outer)",
    "- [ ] C4 — Sem estado global mutável, God objects, imports circulares, duplicação",
    "- [ ] C5 — Exceções à constitution documentadas em ADR (se houver)",
    "- [ ] C6 — Funções ≤ 40 linhas, arquivos ≤ 400 linhas, complexidade ≤ 10",
    "- [ ] C7 — Cobertura de testes ≥ 80% linhas, 100% branches em domínio",
    "- [ ] C8 — TODO/FIXME com ticket associado (formato TODO(#N))",
    "",
    "---",
    "",
    `*Planejado: ${timestamp}*`,
    "*Status: Draft — requer architecture review*",
    "",
  ].join("\n");
}
