import type { TemplatePayload } from "../../types/artifacts.js";

export function testPlanTemplate(payload: TemplatePayload): string {
  const { featureName, featureId, timestamp } = payload;
  return [
    `# Test Plan: ${featureName} (${featureId})`,
    "",
    "## Test Strategy",
    "<!-- Overall testing approach for this feature -->",
    "",
    "## Unit Tests",
    "",
    "### Per Contract",
    "| Contract (function/class) | Test File | Edge Cases Covered |",
    "|---------------------------|-----------|-------------------|",
    "| `<!-- contract -->` | `<!-- test path -->` | <!-- edge cases --> |",
    "",
    "## Integration Tests",
    "",
    "### Per Flow",
    "| Flow | Test File | Dependencies Mocked |",
    "|------|-----------|-------------------|",
    "| `<!-- flow -->` | `<!-- test path -->` | <!-- mocks --> |",
    "",
    "## Edge Cases",
    "- [ ] <!-- edge case 1 -->",
    "- [ ] <!-- edge case 2 -->",
    "- [ ] <!-- edge case 3 -->",
    "",
    "## Error Scenarios",
    "- [ ] <!-- error scenario 1: expected behavior -->",
    "- [ ] <!-- error scenario 2: expected behavior -->",
    "",
    "## Regression Coverage",
    "<!-- Tests that must continue passing after this feature -->",
    "| Existing Test | Reason for Inclusion |",
    "|--------------|---------------------|",
    "| `<!-- test -->` | <!-- reason --> |",
    "",
    "## Verification Commands",
    "```bash",
    "# Run all tests for this feature",
    "npx vitest run test/unit/<!-- feature --> --reporter=verbose",
    "",
    "# Run with coverage",
    "npx vitest run --coverage",
    "```",
    "",
    "## Coverage Targets",
    "- Lines: >= 80%",
    "- Branches: >= 80%",
    "- Functions: >= 80%",
    "- Domain branches: 100%",
    "",
    "---",
    "",
    `*Generated: ${timestamp}*`,
    "*Status: Draft*",
    "",
  ].join("\n");
}
