import type { TemplatePayload } from "../../types/artifacts.js";

export function actionsTemplate(payload: TemplatePayload): string {
  const { featureName, timestamp } = payload;
  return [
    `# Actions: ${featureName}`,
    "",
    "> Cada ação é atômica, verificável e rastreável. Nenhuma ação é considerada pronta sem evidência.",
    "",
    "> **Guia rápido:**",
    "> - T001, T002... — cada ação é UMA unidade de trabalho (1 commit, 1 arquivo, 1 teste)",
    "> - Status: [ ] Pendente / [~] Em progresso / [X] Concluída / [!] Bloqueada",
    "> - ✅ Bom: `T001 — Implementar entidade Subscription com invariantes de status`",
    "> - ❌ Ruim (reprovado): `T001 — Implementar feature de cancelamento` (ação grande demais, ambígua)",
    "",
    "## Pre-requisites",
    "- [ ] requirements.md completo e revisado",
    "- [ ] roadmap.md aprovado em architecture review",
    "- [ ] test-plan.md definido",
    "- [ ] Constitution check passando (C1-C8)",
    "",
    "## Action List",
    "",
    "### T001 — <!-- título da ação -->",
    "",
    "| Campo | Valor |",
    "|-------|-------|",
    "| **Alvo exato** | `src/domain/<!-- Entity -->.ts` |",
    "| **Camada** | `Domínio` |",
    "| **Contrato esperado** | `<!-- assinatura -->` |",
    "| **Teste associado** | `test/unit/<!-- Test -->.test.ts` |",
    "| **Comando de verificação** | `npx vitest run test/unit/<!-- Test -->.test.ts` |",
    "| **Evidência esperada** | <!-- N testes passando, coverage ≥ 80% --> |",
    "| **Risco** | `low` / `medium` / `high` — <!-- descrever --> |",
    "| **Dependências** | <!-- T000 (descrição), ou 'nenhuma' --> |",
    "| **Status** | [ ] Pendente / [~] Em progresso / [X] Concluída / [!] Bloqueada |",
    "",
    "### T002 — <!-- título da ação -->",
    "",
    "| Campo | Valor |",
    "|-------|-------|",
    "| **Alvo exato** | `src/<!-- path -->.ts` |",
    "| **Camada** | `<!-- Domínio / Aplicação / Infra / Interface -->` |",
    "| **Contrato esperado** | `<!-- assinatura -->` |",
    "| **Teste associado** | `test/<!-- path -->.test.ts` |",
    "| **Comando de verificação** | `npx vitest run test/<!-- path -->.test.ts` |",
    "| **Evidência esperada** | <!-- N testes passando --> |",
    "| **Risco** | `low` / `medium` / `high` — <!-- descrever --> |",
    "| **Dependências** | T001 |",
    "| **Status** | [ ] Pendente |",
    "",
    "## Rollback Plan",
    "<!-- Como desfazer cada ação se necessário. -->",
    "- **T001:** `git revert <commit>`",
    "- **T002:** `git revert <commit>`",
    "",
    "## Verification Suite",
    "```bash",
    "# Antes de declarar qualquer ação concluída, execute:",
    "npx vitest run          # todos os testes",
    "npx tsc --noEmit        # typecheck",
    "npx eslint src/         # lint",
    "```",
    "",
    "---",
    "",
    `*Gerado: ${timestamp}*`,
    "*Completion: 0%*",
    "",
  ].join("\n");
}
