import type { TemplatePayload } from "../../types/artifacts.js";

function pedagogy(what: string, good: string, bad: string, criteria: string): string {
  return [
    `<!--`,
    `  📖 O QUE ESCREVER AQUI:`,
    `  ${what}`,
    ``,
    `  ✅ EXEMPLO BOM (passaria nos checks):`,
    `  ${good}`,
    ``,
    `  ❌ EXEMPLO RUIM (seria reprovado por genérico):`,
    `  ${bad}`,
    ``,
    `  📏 CRITÉRIO DE SUFICIÊNCIA:`,
    `  ${criteria}`,
    `-->`,
  ].join("\n");
}

export function requirementsTemplate(payload: TemplatePayload): string {
  const { featureName, featureId, timestamp } = payload;
  return [
    `# Feature: ${featureName} (${featureId})`,
    "",
    "> Spec-Driven Development: entender → especificar → planejar → testar → implementar → verificar.",
    "",
    "> ⚠️ Texto genérico será reprovado nos checks de qualidade (score < 70/100).",
    "> Cada seção tem um critério mínimo de suficiência. Leia os exemplos antes de preencher.",
    "",
    "## Descrição Funcional",
    pedagogy(
      "Explique o PROBLEMA de negócio que esta feature resolve. Use linguagem que um product manager entenderia. NÃO descreva a solução técnica ainda.",
      '"Permite que usuários cancelem suas assinaturas em até 3 cliques, sem falar com suporte. Atualmente o cancelamento exige email para support@empresa.com e leva até 5 dias úteis. Isso afeta ~200 usuários/mês."',
      '"Feature de cancelamento de assinatura." (genérico, não quantifica, não descreve problema)',
      "Descreve o problema (não a solução), nomeia quem usa, quantifica o impacto (tempo, dinheiro, usuários)",
    ),
    "<!-- Descreva qual problema de negócio esta feature resolve. NÃO a solução técnica. -->",
    "",
    "## Comportamento Esperado",
    pedagogy(
      "Descreva COMO o sistema deve se comportar depois que a feature estiver implementada. Use o formato: 'Quando [ator] faz [ação], o sistema [reação]'.",
      '"Quando o usuário clica em Cancelar Assinatura, o sistema exibe uma confirmação com a data de término. Ao confirmar, a assinatura muda para status=canceling e um email é enviado. O usuário vê uma tela de confirmação."',
      '"O sistema deve permitir cancelamento." (vago, não descreve fluxo, estados ou atores)',
      "Pelo menos 2 comportamentos descritos no formato ator → ação → reação. Cobre fluxo principal e ao menos 1 alternativa.",
    ),
    "<!-- Como o sistema deve se comportar quando a feature estiver implementada? Use ator → ação → reação. -->",
    "",
    "## Invariantes de Domínio",
    pedagogy(
      "Regras que SEMPRE devem ser verdadeiras, independentemente do estado do sistema. São leis imutáveis do domínio. Ex: 'Saldo nunca pode ser negativo', 'Email deve ser único'.",
      '"Uma assinatura não pode estar simultaneamente ativa e cancelada. O status de cobrança deve ser consistente com o status da assinatura. Nenhum cancelamento pode ocorrer sem registro de auditoria."',
      '"- O sistema deve funcionar corretamente" (não é invariante, é wishful thinking)',
      "Pelo menos 2 invariantes booleanas (sempre/nunca). Cada uma é falseável — dá pra testar se viola.",
    ),
    "- ",
    "",
    "## Entradas",
    pedagogy(
      "Liste os dados de entrada: parâmetros de API, campos de formulário, payloads. Para cada um: nome, tipo, obrigatório?, validações.",
      '"- subscriptionId: string (UUID v4), obrigatório, deve pertencer ao usuário autenticado.\\n- reason: string (opcional), max 500 chars, motivo do cancelamento."',
      '"- Dados do usuário" (vago, não especifica campos, tipos ou validações)',
      "Cada entrada tem nome, tipo, obrigatoriedade e ao menos 1 regra de validação.",
    ),
    "- ",
    "",
    "## Saídas",
    pedagogy(
      "Liste as saídas: respostas da API, eventos emitidos, efeitos colaterais. Para cada uma: formato, conteúdo, código HTTP (se API).",
      '"- 200 OK: { subscriptionId, newStatus: \\"canceling\\", cancelDate: ISO8601, refundAmount: number }\\n"- Evento: SubscriptionCancelled { subscriptionId, userId, timestamp }\\n"- Email: confirmação de cancelamento enviado para email do usuário"',
      '"- Resposta JSON" (não especifica schema, campos ou eventos)',
      "Cada saída tem formato e conteúdo especificados. Para APIs, código HTTP incluído.",
    ),
    "- ",
    "",
    "## Regras de Negócio",
    pedagogy(
      "Regras específicas que governam ESTA feature. Use numeração R01, R02. Cada regra deve ser testável (verdadeira ou falsa em cada cenário).",
      '"- R01: Assinatura só pode ser cancelada se status = active ou past_due.\\n- R02: Se cancelamento ocorrer até 7 dias após cobrança, reembolso é automático.\\n- R03: Após cancelamento, acesso aos recursos premium continua até o fim do ciclo de cobrança já pago."',
      '"- R01: O sistema deve processar cancelamentos corretamente" (não é regra, é tautologia)',
      "Pelo menos 3 regras numeradas. Cada regra é falseável e testável isoladamente.",
    ),
    "- R01: ",
    "- R02: ",
    "",
    "## Dados Persistidos",
    pedagogy(
      "O que será armazenado? Em qual tabela/modelo/coleção? Quais campos novos ou modificados?",
      '"- Modelo Subscription: novo campo cancelledAt (datetime, nullable), novo campo cancelReason (string, nullable)\\n- Nova tabela: cancellation_audit_log (id, subscriptionId, userId, reason, timestamp)\\n- Nenhum dado é deletado — cancelamento é soft (status muda para cancelling/cancelled)"',
      '"- Dados no banco" (não especifica modelos, campos, ou estratégia)',
      "Entidades e campos novos/modificados listados. Estratégia de persistência clara (soft delete? hard delete?).",
    ),
    "- ",
    "",
    "## Integrações Externas",
    pedagogy(
      "APIs externas, serviços, sistemas afetados. Para cada um: qual endpoint, qual contrato, o que esperar de falha.",
      '"- Stripe API: POST /v1/subscriptions/{id} (cancel subscription), resposta esperada: subscription object com status=canceled\\n"- Email Service (SendGrid): POST /v3/mail/send, template: subscription-cancellation\\n"- Falha no Stripe: retry 3x com exponential backoff, se todas falharem → status=cancellation_failed + alerta"',
      '"- Gateway de pagamento" (não especifica qual, quais endpoints, ou tratamento de erro)',
      "Cada integração: endpoint exato ou operação, contrato esperado, estratégia de falha.",
    ),
    "- ",
    "",
    "## Critérios de Aceitação",
    pedagogy(
      "Formato Given/When/Then (Gherkin). Devem ser MENSURÁVEIS e TESTÁVEIS. Mínimo 3 cenários, incluindo ao menos 1 de erro.",
      `"- [ ] Cenário 1: Given usuário logado com assinatura ativa, When clica em Cancelar e confirma, Then status muda para cancelling e email é enviado.\\n- [ ] Cenário 2: Given assinatura já cancelada, When usuário tenta cancelar novamente, Then erro 409 'already cancelled'.\\n- [ ] Cenário 3: Given usuário não autenticado, When tenta acessar endpoint de cancelamento, Then erro 401."`,
      '"- [ ] Cenário 1: Given usuário, When cancela, Then funciona" (sem dados concretos, sem edge cases)',
      "Mínimo 3 cenários em Gherkin. Pelo menos 1 cenário de erro/edge case. Cada Then tem verificação concreta (status code, mensagem, estado).",
    ),
    "- [ ] **Cenário 1:** Given <!-- contexto -->, When <!-- ação -->, Then <!-- resultado esperado -->",
    "- [ ] **Cenário 2:** Given <!-- contexto -->, When <!-- ação -->, Then <!-- resultado esperado -->",
    "- [ ] **Cenário 3:** Given <!-- contexto -->, When <!-- ação -->, Then <!-- resultado esperado -->",
    "",
    "## Casos de Erro",
    pedagogy(
      "Para cada possível falha, descreva o comportamento esperado. Cobrir: erros de validação, erros de sistema, timeouts, conflitos.",
      '"- Erro 1: subscriptionId inválido → 400 Bad Request com { error: \\"INVALID_SUBSCRIPTION_ID\\" }\\n- Erro 2: Stripe API indisponível → retry 3x, depois 502 Bad Gateway com { error: \\"PAYMENT_PROVIDER_UNAVAILABLE\\" }\\n- Erro 3: Conflito de concorrência → 409 Conflict com { error: \\"SUBSCRIPTION_ALREADY_CANCELING\\" }"',
      '"- Erro 1: Algo deu errado → mostrar mensagem de erro" (não especifica código, payload, ou recuperação)',
      "Pelo menos 3 erros com: gatilho, código HTTP (se API), payload de resposta, estratégia de recuperação (se houver).",
    ),
    "- **Erro 1:** <!-- descrição → comportamento esperado -->",
    "- **Erro 2:** <!-- descrição → comportamento esperado -->",
    "",
    "## Casos Extremos",
    pedagogy(
      "Edge cases: valores nulos, limites, condições de corrida, timeouts, concorrência. O que acontece no pior cenário?",
      '"- [ ] Usuário clica em Cancelar 2x em menos de 1 segundo (race condition) → idempotência: segunda chamada retorna 200 com status já existente\\n- [ ] Assinatura vence durante o processo de cancelamento → prevalece o cancelamento\\n- [ ] Usuário com 0 assinaturas ativas tenta cancelar → 404"',
      '"- [ ] Sistema lento" (não é edge case concreto, não especifica comportamento)',
      "Pelo menos 3 edge cases concretos. Cada um especifica condição exata e comportamento esperado.",
    ),
    "- [ ] <!-- edge case 1 -->",
    "- [ ] <!-- edge case 2 -->",
    "",
    "## Restrições Técnicas",
    pedagogy(
      "Limitações técnicas, versões de dependências, compatibilidade, restrições de infraestrutura.",
      '"- Node.js >= 18 (usamos crypto.randomUUID nativo)\\n- Stripe API versão 2023-08-16 ou superior\\n- Transaction com isolation level SERIALIZABLE para evitar race condition\\n- Não usar mais de 100 conexões simultâneas ao banco durante o cancelamento"',
      '"- Usar boas práticas" (não é restrição técnica)',
      "Restrições específicas e verificáveis. Se não houver restrições técnicas relevantes, explicite: 'Nenhuma restrição técnica específica além do stack padrão do projeto.'",
    ),
    "- ",
    "",
    "## Escopo Negativo",
    pedagogy(
      "EXPLICITAMENTE o que NÃO está incluso. Isso protege contra scope creep e deixa claro para a IA o que não deve implementar.",
      '"- Esta feature NÃO inclui: pausar assinatura (só cancelamento definitivo)\\n- Esta feature NÃO inclui: mudança de plano (downgrade/upgrade)\\n- Esta feature NÃO inclui: reembolso retroativo para cancelamentos após 7 dias\\n- Esta feature NÃO inclui: reativação de assinatura cancelada\\n- Esta feature NÃO inclui: interface mobile nativa (só web responsivo)"',
      '"- Esta feature NÃO inclui: bugs" (não é escopo negativo, é wishful thinking)',
      "Mínimo 3 itens explícitos de não-escopo. Cada item é específico e falseável (dá pra verificar se foi implementado ou não).",
    ),
    "- Esta feature NÃO inclui: <!-- descrever -->",
    "- Esta feature NÃO inclui: <!-- descrever -->",
    "- Esta feature NÃO inclui: <!-- descrever -->",
    "",
    "## Requisitos Não-Funcionais",
    pedagogy(
      "Performance, segurança, escalabilidade, observabilidade. Seja específico com números e métricas.",
      '"- Performance: endpoint de cancelamento responde em < 500ms p95, < 2s p99\\n- Segurança: apenas o próprio usuário ou admin pode cancelar (verificação de ownership)\\n- Observabilidade: métrica subscription_cancellations_total com labels {status, reason}, log estruturado em JSON com correlationId\\n- Confiabilidade: cancelamento deve ser atômico (ou tudo or nada — usar transação)"',
      '"- Performance: rápido\\n- Segurança: seguro" (sem métricas, sem critérios objetivos)',
      "Pelo menos 1 requisito por categoria relevante (performance, segurança, observabilidade). Cada um com métrica ou critério objetivo.",
    ),
    "- **Performance:** <!-- requisito -->",
    "- **Segurança:** <!-- requisito -->",
    "- **Observabilidade:** <!-- requisito -->",
    "",
    "## Riscos de Manutenção",
    pedagogy(
      "O que pode quebrar no futuro? O que é sensível a mudanças? Pense em dependências externas, migrações, alterações de schema.",
      '"- Risco 1: Mudança na API do Stripe → mitigação: usar versão fixa da API + testes de contrato com mock do Stripe\\n- Risco 2: Corrupção de dados se migração falhar → mitigação: migration com rollback automático + backup pré-migration\\n- Risco 3: Acoplamento com módulo de billing → mitigação: interface BillingPort com adapter StripeBillingAdapter"',
      '"- Risco 1: Código pode ter bugs → mitigação: testar bem" (genérico, não identifica riscos reais)',
      "Pelo menos 2 riscos específicos com mitigação concreta. Cada risco é um evento futuro plausível, não genérico.",
    ),
    "- **Risco 1:** <!-- descrição → mitigação -->",
    "- **Risco 2:** <!-- descrição → mitigação -->",
    "",
    "## Dúvidas [DOUBT]",
    "<!-- ⚠️ Marcadores [DOUBT] BLOQUEIAM o avanço para feature-design. -->",
    "<!-- Resolva cada dúvida antes de prosseguir. Use devflow clarify ou edite manualmente. -->",
    "<!-- Se não houver dúvidas, mantenha esta seção vazia (sem [DOUBT] markers). -->",
    "- [ ] [DOUBT] <!-- pergunta -->",
    "",
    "---",
    "",
    `*Gerado: ${timestamp}*`,
    "*Status: Draft — requer revisão de requirements*",
    "*Use `devflow next` para ver o diagnóstico e próximos passos.*",
    "",
  ].join("\n");
}
