import type { TemplatePayload } from "../../types/artifacts.js";

function pedagogyNote(what: string, good: string, bad: string): string {
  return [
    `<!--`,
    `  📖 ${what}`,
    `  ✅ Bom: ${good}`,
    `  ❌ Ruim (reprovado): ${bad}`,
    `-->`,
  ].join("\n");
}

export function roadmapTemplate(payload: TemplatePayload): string {
  const { featureName, timestamp } = payload;
  return [
    `# Architectural Roadmap: ${featureName}`,
    "",
    "> Este documento define COMO a feature será implementada, não apenas O QUE ela faz.",
    "> ⚠️ Seções vagas serão reprovadas. Toda decisão de design exige justificativa.",
    "",
    "> **Guia rápido:**",
    "> - Camadas: Domínio (regras de negócio), Aplicação (orquestração), Infra (IO), Interface (entrega)",
    "> - Padrões adotados: justifique cada um com o problema que resolve, não com buzzwords",
    "> - Padrões rejeitados: tão importante quanto os adotados — mostra que você considerou alternativas",
    "> - Riscos de acoplamento: o que pode quebrar se módulo X mudar?",
    "",
    "## Desenho Arquitetural",
    pedagogyNote(
      "Diagrama Mermaid mostrando componentes, fluxo de dados e direção das dependências.",
      "graph TD; User->>Controller->>UseCase->>Repository; Repository-->>Domain",
      "(vazio, sem diagrama)",
    ),
    "```mermaid",
    "<!-- Diagrama de arquitetura: componentes, relações, fluxo de dados -->",
    "```",
    "",
    "## Camadas Envolvidas",
    pedagogyNote(
      "Marque TODAS as camadas que esta feature toca. Uma feature típica toca 3-4 camadas.",
      "Domínio (Subscription), Aplicação (CancelSubscriptionUseCase), Interface (SubscriptionController)",
      "(nenhuma marcada ou todas marcadas sem justificativa)",
    ),
    "- [ ] Domínio (entidades, value objects, agregados)",
    "- [ ] Aplicação (use cases, serviços de aplicação)",
    "- [ ] Infraestrutura (repositories, adapters, clientes HTTP)",
    "- [ ] Interface (controllers, CLI commands, handlers)",
    "",
    "## Classes/Módulos Previstos",
    pedagogyNote(
      "Cada classe com UMA responsabilidade (SRP). Se uma classe tem 'e' na descrição, divida em duas.",
      "CancelSubscriptionUseCase — orquestrar cancelamento de assinatura — Aplicação",
      "SubscriptionService — gerencia assinaturas E envia emails E calcula reembolso (3 responsabilidades, reprovado)",
    ),
    "| Classe/Módulo | Responsabilidade | Camada |",
    "|--------------|-----------------|--------|",
    "| `<!-- NomeClasse -->` | `<!-- responsabilidade única -->` | `<!-- camada -->` |",
    "",
    "## Padrões de Projeto Adotados",
    pedagogyNote(
      "Nomeie o padrão E explique qual problema concreto ele resolve NESTA feature.",
      "Repository Pattern — desacopla domínio da implementação de banco, permitindo trocar Postgres por MongoDB sem alterar regras de negócio",
      "Repository Pattern (sem justificativa de por que este pattern é necessário aqui)",
    ),
    "- **Padrão:** <!-- nome → justificativa -->",
    "- **Padrão:** <!-- nome → justificativa -->",
    "",
    "## Padrões Rejeitados",
    pedagogyNote(
      "Padrões que você considerou mas decidiu NÃO usar. Mostra pensamento crítico sobre design.",
      "CQRS — rejeitado porque a feature não tem complexidade de leitura/escrita que justifique segregação",
      "(seção vazia — parece que você não considerou alternativas)",
    ),
    "- **Padrão:** <!-- nome → por que foi rejeitado -->",
    "",
    "## Interfaces Necessárias",
    "<!-- Contratos que as implementações devem satisfazer. -->",
    "```typescript",
    "// interface ISubscriptionRepository { cancel(id: string): Promise<void>; }",
    "// interface INotificationService { sendCancellationEmail(userId: string): Promise<void>; }",
    "```",
    "",
    "## Repositories",
    "- `<!-- IEntityRepository -->` — responsável por <!-- entidade -->",
    "",
    "## Adapters",
    "- `<!-- NomeAdapter -->` — implementa `<!-- interface -->` usando `<!-- tecnologia -->`",
    "",
    "## Serviços de Domínio",
    "- `<!-- NomeService -->` — responsável por <!-- regra de negócio -->",
    "",
    "## Riscos de Acoplamento",
    pedagogyNote(
      "Identifique dependências entre módulos e o que quebra se um mudar. Use dependency-cruiser para validar.",
      "CancelSubscriptionUseCase → StripeAdapter: se a API do Stripe mudar, o adapter quebra, mas o UseCase permanece isolado pela interface",
      "(vazio — 'não há riscos' é falso em qualquer sistema com mais de 1 módulo)",
    ),
    "- **Risco:** <!-- dependência → mitigação -->",
    "",
    "## Impacto em Código Legado",
    "| Arquivo | Tipo de Mudança | Risco |",
    "|---------|---------------|------|",
    "| `<!-- path -->` | `<!-- mod/create/delete -->` | `<!-- low/medium/high -->` |",
    "",
    "## Estratégia de Rollback",
    pedagogyNote(
      "Se esta feature quebrar produção, como desfazê-la em < 5 minutos?",
      "Reverter merge da branch + executar rollback-migration.ts (remove coluna cancelledAt da tabela subscriptions)",
      "Reverter merge (não considera migrações de banco ou dados já escritos)",
    ),
    "- Reverter merge da branch `feature/<!-- nome -->`",
    "- Executar script de rollback: `<!-- comando -->` (se aplicável)",
    "",
    "## Verificação de Constitution",
    "<!-- Checklist de conformidade com a constitution do projeto. -->",
    "- [ ] C1 — Regras de negócio encapsuladas em domínio/serviços/use cases",
    "- [ ] C2 — Infraestrutura acessada por interfaces/adapters/repositories",
    "- [ ] C3 — Dependências apontam para dentro (inner layers não dependem de outer)",
    "- [ ] C4 — Sem estado global mutável, God objects, imports circulares, duplicação",
    "- [ ] C5 — Exceções à constitution documentadas em ADR (se houver)",
    "- [ ] C6 — Funções ≤ 40 linhas, arquivos ≤ 400 linhas, complexidade ≤ 10",
    "- [ ] C7 — Cobertura de testes ≥ 80% linhas, 100% branches em domínio",
    "- [ ] C8 — TODO/FIXME com ticket associado (formato TODO(#N))",
    "",
    "---",
    "",
    `*Planejado: ${timestamp}*`,
    "*Status: Draft — requer architecture review*",
    "",
  ].join("\n");
}
