import path from "node:path";
import { atomicWrite } from "../utils/fs.js";

interface DoDCheck {
  id: string;
  description: string;
  category: string;
  passed: boolean;
  evidence: string;
  blocking: boolean;
}

export interface AuditInput {
  featureId: string;
  featureName: string;
  rootPath: string;
  dodChecks: DoDCheck[];
  ciStatus?: string;
  implementer?: string;
  reviewer?: string;
  gatekeeper?: string;
}

/**
 * Generate engineering-review.md from all gathered evidence.
 */
export async function generateEngineeringReview(input: AuditInput): Promise<string> {
  const { featureId, featureName, dodChecks, implementer, reviewer } = input;
  const now = new Date().toISOString();
  const totalPassed = dodChecks.filter((c) => c.passed).length;
  const total = dodChecks.length;
  const blockingFailed = dodChecks.filter((c) => c.blocking && !c.passed).length;

  const report = `# Engineering Review — ${featureName}

> **Feature:** ${featureId}
> **Generated:** ${now}
> **Status:** ${blockingFailed === 0 ? "✅ Ready for Review" : "❌ Blocked"}

## State & Confidence

- **DoD Checks Passed:** ${totalPassed}/${total}
- **Blocking Failures:** ${blockingFailed}
- **Implementer:** ${implementer || "unknown"}
- **Reviewer:** ${reviewer || "pending"}

## Constitution Check Summary

| Check | Result |
|-------|--------|
${dodChecks.filter((c) => c.id === "4").map((c) => `| Constitution (${c.id}) | ${c.passed ? "✓ Pass" : "✖ Fail"} |`).join("\n")}

## Deterministic Checks Summary

| # | Check | Result |
|---|-------|--------|
${dodChecks.filter((c) => c.category === "deterministic").map((c) => `| ${c.id} | ${c.description} | ${c.passed ? "✓" : "✖"} |`).join("\n")}

## Artifact Checks

| # | Check | Result |
|---|-------|--------|
${dodChecks.filter((c) => c.category === "artifact").map((c) => `| ${c.id} | ${c.description} | ${c.passed ? "✓" : "✖"} |`).join("\n")}

## Process & Review Checks

| # | Check | Result |
|---|-------|--------|
${dodChecks.filter((c) => c.category === "process" || c.category === "review").map((c) => `| ${c.id} | ${c.description} | ${c.passed ? "✓" : "✖"} |`).join("\n")}

## Risk Assessment

${blockingFailed > 0
    ? `⚠️ ${blockingFailed} blocking check(s) failed. See above for details.`
    : "✅ All blocking checks passed. Feature is ready for gatekeeper review."}

## Evidence Integrity

${dodChecks.filter((c) => !c.passed).map((c) => `- **${c.id}**: ${c.evidence}`).join("\n") || "- All checks passing — no issues to report"}
`;

  const reportPath = path.join(input.rootPath, ".devflow", "audits", "engineering-review.md");
  await atomicWrite(reportPath, report);

  return reportPath;
}

/**
 * Generate release-audit.md for gatekeeper sign-off.
 */
export async function generateReleaseAudit(input: AuditInput): Promise<string> {
  const { featureId, featureName, dodChecks, ciStatus, implementer, gatekeeper } = input;
  const now = new Date().toISOString();
  const totalPassed = dodChecks.filter((c) => c.passed).length;
  const total = dodChecks.length;

  const report = `# Release Audit — ${featureName}

> **Feature:** ${featureId}
> **Generated:** ${now}

## Definition of Done Matrix

**Result:** ${totalPassed}/${total} checks passed

| # | Check | Category | Passed | Blocking |
|---|-------|----------|--------|----------|
${dodChecks.map((c) => `| ${c.id} | ${c.description} | ${c.category} | ${c.passed ? "✓" : "✖"} | ${c.blocking ? "🔴" : "🟡"} |`).join("\n")}

## CI Verification

- **Status:** ${ciStatus || "not configured"}
- **Provider:** GitHub Actions

## Constitution Compliance Certificate

${dodChecks.find((c) => c.id === "4")?.passed
    ? "✅ All constitution rules pass. Feature is constitution-compliant."
    : "❌ Constitution violations found. See engineering-review.md for details."}

## Coverage Report Summary

${dodChecks.find((c) => c.id === "8")?.evidence || "Coverage not available"}

## Regression Risk Assessment

- **Legacy Impact:** ${dodChecks.find((c) => c.id === "10")?.passed ? "Documented" : "Not documented"}
- **Regression Watch:** ${dodChecks.find((c) => c.id === "11")?.passed ? "Active" : "Not configured"}

## Gatekeeper Sign-Off

- **Implementer:** ${implementer || "unknown"}
- **Gatekeeper:** ${gatekeeper || "pending"}
- **Date:** ${now}

---

> This report is auto-generated by Devflow. It provides auditable evidence of engineering process adherence.
> **Principle:** "Não confie em mim — aqui estão as provas."
`;

  const reportPath = path.join(input.rootPath, ".devflow", "audits", "release-audit.md");
  await atomicWrite(reportPath, report);

  return reportPath;
}
