/**
 * devflow actions generate — Generate GitHub Actions workflow from project config
 *
 * Reads .devflow/config.json and generates a .github/workflows/devflow-governance.yml
 * workflow file for CI/CD integration.
 *
 * Output: pipe-safe JSON via stdout, banner via stderr.
 */
import path from "node:path";
import fs from "node:fs/promises";
import { safeReadFile } from "../kernel/utils/fs.js";
import pc from "picocolors";

export interface ActionsGenerateResult {
  featureId: string;
  workflowPath: string;
  workflowContent: string;
  yamlValid: boolean;
  yamlErrors: string[];
  written: boolean;
  verdict: "generated" | "written" | "no-config" | "invalid";
}

/**
 * Basic YAML syntax validation.
 * Checks for common syntax issues without a full YAML parser.
 */
function validateYamlSyntax(content: string): string[] {
  const errors: string[] = [];
  const lines = content.split("\n");

  let inMultilineString = false;
  const indentStack: number[] = [];

  for (let i = 0; i < lines.length; i++) {
    const line = lines[i]!;
    const trimmed = line.trim();

    // Skip empty lines and comments
    if (trimmed === "" || trimmed.startsWith("#")) {
      continue;
    }

    // Track indentation for consistency
    const indent = line.search(/\S/);
    if (indent >= 0) {
      // Remove indentation items that are deeper than current
      while (indentStack.length > 0 && indentStack[indentStack.length - 1]! > indent) {
        indentStack.pop();
      }

      if (indentStack.length > 0 && indentStack[indentStack.length - 1]! < indent) {
        // New nesting level — should be multiple of 2 (standard YAML)
        const diff = indent - indentStack[indentStack.length - 1]!;
        if (diff % 2 !== 0) {
          errors.push(`Line ${i + 1}: Inconsistent indentation (${diff} spaces, expected multiple of 2)`);
        }
        indentStack.push(indent);
      } else if (indentStack.length === 0 && indent > 0) {
        errors.push(`Line ${i + 1}: Top-level content should have 0 indentation`);
      } else if (indentStack.length === 0) {
        indentStack.push(0);
      }

      // Check for unclosed quotes
      if (!inMultilineString) {
        const singleQuotes = (trimmed.match(/'/g) || []).length;
        const doubleQuotes = (trimmed.match(/"/g) || []).length;
        if (singleQuotes % 2 !== 0 || doubleQuotes % 2 !== 0) {
          errors.push(`Line ${i + 1}: Unclosed quote detected`);
        }
      }

      // Check for tabs
      if (line.includes("\t")) {
        errors.push(`Line ${i + 1}: Tab character detected — use spaces for YAML indentation`);
      }
    }
  }

  return errors;
}

/**
 * Generate the GitHub Actions workflow YAML content.
 * Template adapted from the README.md GitHub Actions section.
 */
function generateWorkflowContent(
  projectName: string,
  featureId: string,
): string {
  const safeName = projectName.replace(/[^a-zA-Z0-9_-]/g, "-").toLowerCase();

  return `# Devflow Governance — ${projectName}
# Auto-generated by \`devflow actions generate\`
# Run Devflow governance checks on every PR

name: Devflow PR Governance — ${safeName}

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  governance:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm ci || npm install

      - name: Initialize Devflow
        run: npx @tjsasakinpm/devflow init

      - name: Verify feature completion
        run: npx @tjsasakinpm/devflow feature complete ${featureId}

      - name: Adversarial review
        run: npx @tjsasakinpm/devflow adversarial-review ${featureId}

      - name: Gatekeep approval
        run: npx @tjsasakinpm/devflow gatekeep ${featureId} --approve --actor github-actions

      - name: Audit changes
        run: npx @tjsasakinpm/devflow audit

      - name: Drift check
        run: npx @tjsasakinpm/devflow drift check ${featureId}

      - name: Tests review
        run: npx @tjsasakinpm/devflow tests review ${featureId}

      - name: Summary
        run: |
          echo "## Devflow Governance Results" >> $GITHUB_STEP_SUMMARY
          echo "All governance checks completed successfully." >> $GITHUB_STEP_SUMMARY
`;
}

export async function actionsGenerateCommand(
  cwd: string,
  featureId: string,
  options: { write?: boolean } = {},
): Promise<void> {
  const rootPath = path.resolve(cwd);
  const configPath = path.join(rootPath, ".devflow", "config.json");

  // Load project config
  const configRaw = await safeReadFile(configPath);

  if (!configRaw) {
    const result: ActionsGenerateResult = {
      featureId,
      workflowPath: "",
      workflowContent: "",
      yamlValid: false,
      yamlErrors: [".devflow/config.json not found"],
      written: false,
      verdict: "no-config",
    };

    console.log(JSON.stringify(result, null, 2));

    console.error(
      pc.yellow(`\n${pc.bold("Devflow Actions Generate")}`),
    );
    console.error(pc.yellow(`  Feature: ${featureId}`));
    console.error(pc.red("  .devflow/config.json not found — cannot generate workflow.\n"));
    return;
  }

  let config: { projectName?: string };
  try {
    config = JSON.parse(configRaw);
  } catch {
    const result: ActionsGenerateResult = {
      featureId,
      workflowPath: "",
      workflowContent: "",
      yamlValid: false,
      yamlErrors: ["Invalid .devflow/config.json"],
      written: false,
      verdict: "no-config",
    };

    console.log(JSON.stringify(result, null, 2));

    console.error(pc.red("\n  Invalid .devflow/config.json\n"));
    return;
  }

  const projectName = config.projectName || "my-project";

  // Generate workflow content
  const workflowContent = generateWorkflowContent(projectName, featureId);

  // Validate YAML syntax
  const yamlErrors = validateYamlSyntax(workflowContent);
  const yamlValid = yamlErrors.length === 0;

  const workflowDir = path.join(rootPath, ".github", "workflows");
  const workflowPath = path.join(workflowDir, "devflow-governance.yml");

  let written = false;

  if (options.write && yamlValid) {
    await fs.mkdir(workflowDir, { recursive: true });
    await fs.writeFile(workflowPath, workflowContent, "utf-8");
    written = true;
  }

  const verdict: ActionsGenerateResult["verdict"] = written
    ? "written"
    : yamlValid
      ? "generated"
      : "invalid";

  const result: ActionsGenerateResult = {
    featureId,
    workflowPath: written ? workflowPath : "(not written)",
    workflowContent,
    yamlValid,
    yamlErrors,
    written,
    verdict,
  };

  // JSON output to stdout (pipe-safe)
  console.log(JSON.stringify(result, null, 2));

  // Banner to stderr
  console.error(
    pc.bold("\nDevflow Actions Generate"),
  );
  console.error(pc.dim(`  Feature: ${featureId}`));
  console.error("");

  if (!yamlValid) {
    console.error(pc.red("  Generated YAML has syntax errors:"));
    for (const err of yamlErrors) {
      console.error(pc.red(`    ✗ ${err}`));
    }
  } else if (verdict === "written") {
    console.error(pc.green(`  Workflow written to: ${workflowPath}`));
  } else {
    console.error(pc.yellow("  Workflow generated (not written). Use --write to save."));
    console.error(pc.dim(`  Path: ${workflowPath}`));
  }

  console.error("");
}
